# Generated by Django 5.2.5 on 2025-08-20 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('closed', 'Fermé')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du projet', max_length=255)),
                ('description', models.TextField(help_text='Description détaillée du projet')),
                ('type', models.CharField(help_text='Type de projet', max_length=50)),
                ('date_debut', models.DateField(blank=True, help_text='Date de début du projet (optionnel)', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin du projet (optionnel)', null=True)),
                ('chef_projet', models.ForeignKey(help_text='Utilisateur responsable du projet', on_delete=django.db.models.deletion.CASCADE, related_name='projets_chef', to=settings.AUTH_USER_MODEL)),
                ('collaborateurs', models.ManyToManyField(blank=True, help_text='Liste des collaborateurs', related_name='projets_collaborateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.projet'),
        ),
        migrations.CreateModel(
            name='ProjetCollaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chef', 'Chef de projet'), ('contributeur', 'Contributeur')], default='contributeur', max_length=20)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborateurs_relations', to='issues.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('projet', 'user')},
            },
        ),
    ]
