# Generated by Django 4.2.23 on 2025-08-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
    ]
