# Generated by Django 4.2.23 on 2025-08-01 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0002_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='chef_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets_auteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='type',
            field=models.CharField(choices=[('backend', 'Back-end'), ('frontend', 'Front-end'), ('ios', 'iOS'), ('android', 'Android')], default='backend', max_length=20),
            preserve_default=False,
        ),
    ]
