# Generated by Django 4.2.23 on 2025-08-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_projet_chef_projet_projet_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='author_user',
            new_name='chef_projet',
        ),
    ]
