# Generated by Django 4.2.23 on 2025-08-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_rename_author_user_projet_chef_projet'),
    ]

    operations = [
    ]
